services:
  umida:
    build: .
    container_name: "umida"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - main.datasource.url=jdbc:postgresql://postgres:5432/postgres

  postgres:
    image: "postgres:16.1"
    container_name: "jmix-postgres"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - jmix-main-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  postgres-dwh:
    image: "postgres:16.1"
    container_name: "jmix-dwh"
    ports:
      - "16432:5432"
    environment:
      - POSTGRES_DB=dwh
      - POSTGRES_USER=dwh_reporting
      - POSTGRES_PASSWORD=qweasd123
    volumes:
      - jmix-dwh-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dwh_reporting -d dwh" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    image: adminer
    container_name: "jmix-adminer"
    restart: always
    ports:
      - 8090:8080

  starrocks:
    image: starrocks/allin1-ubuntu:latest
    container_name: starrocks
    restart: unless-stopped
    ports:
      - "8030:8030" # FE HTTP
      - "9020:9020" # FE RPC
      - "9030:9030" # MySQL/JDBC
      - "8040:8040" # BE HTTP
      - "9050:9050" # BE heartbeat
      - "9060:9060" # BE BRPC
    volumes:
      - starrocks_data:/opt/starrocks
    environment:
      - TZ=Asia/Tashkent

volumes:
  jmix-main-db:
    driver: local
  jmix-dwh-db:
    driver: local
  starrocks_data: