services:
  umida:
    build: .
    container_name: "umida"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - main.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - dwh.datasource.url=jdbc:postgresql://postgres-dwh:5432/dwh

  postgres:
    image: "postgres:16.1"
    container_name: "jmix-postgres"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql1234
    volumes:
      - jmix-main-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  postgres-dwh:
    image: "postgres:16.1"
    container_name: "jmix-dwh"
    ports:
      - "16432:5432"
    environment:
      - POSTGRES_DB=dwh
      - POSTGRES_USER=dwh_reporting
      - POSTGRES_PASSWORD=qweasd123
    volumes:
      - jmix-dwh-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dwh_reporting -d dwh" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    image: adminer
    container_name: "jmix-adminer"
    restart: always
    ports:
      - 8090:8080

volumes:
  jmix-main-db:
    driver: local
  jmix-dwh-db:
    driver: local