name: Commit Checks # название нашего workflow
on: # Запускаем workflow при push и pull-request в ветку master.
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
#  build:
#    name: Building the app
#    runs-on: ubuntu-22.04
#    steps:
#      - name: SSH to VPS and build
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USER }}
#          key: ${{ secrets.VPS_SSH_KEY }}
#          script: |
#            mkdir -p /home/deploy/jmix
#            cd /home/deploy/jmix
#            git pull origin master
#            chmod +x gradlew
#            ./gradlew clean publish --no-daemon --stacktrace
#  build-and-deploy:
#    name: Building and Deploy the app
#    runs-on: ubuntu-22.04
#    steps:
#      - name: SSH to VPS and build
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USER }}
#          key: ${{ secrets.VPS_SSH_KEY }}
#          script: |
#            set -e
#
#            mkdir -p /home/deploy
#            cd /home/deploy
#
#            if [ ! -d "jmix/.git" ]; then
#            git clone git@github.com:ravshancha/jmix.git jmix
#            fi
#
#            cd jmix
#            git pull origin master
#
#            chmod +x gradlew
#
#            export NODE_OPTIONS="--max-old-space-size=3072"
#
#            ./gradlew clean bootBuildImage \
#            -Pvaadin.productionMode=true \
#            --no-daemon --stacktrace
#
#            cd docker
#            docker compose down
#            docker compose up -d
  build:
    name: Building
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build production JAR
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          ./gradlew clean bootJar \
            -Pvaadin.productionMode=true \
            -PpremiumRepoUser=${{ secrets.PREMIUM_REPO_USER }} \
            -PpremiumRepoPass=${{ secrets.PREMIUM_REPO_PASS }} \
            --no-daemon

      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/libs/app.jar, docker/Dockerfile, docker/docker-compose.yml"
          target: "/home/deploy/"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy
            docker compose down
            docker compose up -d --build